openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      properties:
        managementCluster:
          title: Managementcluster
          type: boolean
          description: Enable scrape configuration
          default: true
          x-walrus-ui:
            group: Basic
            order: 2
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where the Helm release will be installed.
          default: sveltos-system
          x-walrus-ui:
            group: Basic
            order: 2
        chart_version:
          title: Chart Version
          type: string
          description: The version of the Helm chart.
          default: 0.44.3
          x-walrus-ui:
            group: Basic
            order: 3
        resources:
          title: Resources
          type: object
          description: Resource limits and requests for Pods Helm release.
          default:
            accessManager:
              limits:
                cpu: 500m
                memory: 256Mi
              requests:
                cpu: 10m
                memory: 128Mi
            addonController:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 250m
                memory: 256Mi
            classifierManager:
              limits:
                cpu: 500m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            conversionWebhook:
              limits:
                cpu: 500m
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 64Mi
            eventManager:
              limits:
                cpu: 500m
                memory: 256Mi
              requests:
                cpu: 10m
                memory: 128Mi
            hcManager:
              limits:
                cpu: 500m
                memory: 256Mi
              requests:
                cpu: 10m
                memory: 128Mi
            registerMgmtClusterJob:
              limits:
                cpu: 500m
                memory: 256Mi
              requests:
                cpu: 250m
                memory: 128Mi
            scManager:
              limits:
                cpu: 500m
                memory: 256Mi
              requests:
                cpu: 10m
                memory: 128Mi
            shardController:
              limits:
                cpu: 500m
                memory: 256Mi
              requests:
                cpu: 10m
                memory: 128Mi
            uiBackendManager:
              limits:
                cpu: 500m
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 64Mi
          additionalProperties:
            properties:
              limits:
                properties:
                  cpu:
                    title: Cpu
                    type: string
                    x-walrus-ui:
                      order: 1
                  memory:
                    title: Memory
                    type: string
                    x-walrus-ui:
                      order: 2
                required:
                - cpu
                - memory
                title: Limits
                type: object
                x-walrus-ui:
                  colSpan: 12
                  order: 1
              requests:
                properties:
                  cpu:
                    title: Cpu
                    type: string
                    x-walrus-ui:
                      order: 1
                  memory:
                    title: Memory
                    type: string
                    x-walrus-ui:
                      order: 2
                required:
                - cpu
                - memory
                title: Requests
                type: object
                x-walrus-ui:
                  colSpan: 12
                  order: 2
            required:
            - limits
            - requests
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 9
        class_name:
          title: Class Name
          type: string
          description: Ingress className
          default: nginx
          x-walrus-ui:
            group: Basic
            order: 8
        issuer_kind:
          title: Issuer Kind
          type: string
          description: 'origin issuer kind for annotation cert-manager.io/issuer-kind:'
          default: ClusterOriginIssuer
          x-walrus-ui:
            group: Basic
            order: 7
        issuer_name:
          title: Issuer Name
          type: string
          description: 'origin issuer name for annotation cert-manager.io/issuer:'
          default: origin-ca-issuer
          x-walrus-ui:
            group: Basic
            order: 6
        dashboard_chart_version:
          title: Dashboard Chart Version
          type: string
          description: The version of the Sveltos Dashboard Helm chart.
          default: 0.44.0
          x-walrus-ui:
            group: Basic
            order: 4
        domain_name:
          title: Domain Name
          type: string
          description: domain name for sveltos, e.g. 'dev.domainname.com'
          default: dev.domainname.com
          x-walrus-ui:
            group: Basic
            order: 5
      x-walrus-ui:
        groupOrder:
        - Basic
